[package]
name = "reece_smith_merchant"
version = "0.1.0"
edition = "2024"

[lib]
name         = "reece_smith_merchant"
crate-type   = ["rlib", "cdylib"]

[dependencies]


[build-dependencies]
cbindgen = "0.29.0"
